name: "Test build of image when Dockerfile is changed"

on:
  push:
    paths:
    - 'Dockerfile'
    branches-ignore:
    - main
  pull_request:
    paths:
    - 'Dockerfile'
  workflow_dispatch:

jobs:
  rebuild-container:
    name: "Build image with cache"
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0
        with:
          platforms: linux/arm64
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.6.0
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: Build x86_64 image
        id: docker_build_amd64
        uses: docker/build-push-action@v4.1.1
        with:
          push: false
          load: true
          platforms: linux/amd64
          tags: sparrow-server:ubuntu-test
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/sparrow-server:latest
      - 
        name: Build ARMv8 image
        id: docker_build_arm64
        uses: docker/build-push-action@v4.1.1
        with:
          push: false
          load: true
          platforms: linux/arm64
          tags: sparrow-server:ubuntu-test
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/sparrow-server:latest
